version: '3.8'

services:
  # API Service
  api:
    image: ghcr.io/gitraicommerce/firstmake-api:${VERSION:-latest}
    container_name: firstmake-api
    restart: unless-stopped
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/data/firstmake.db
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./data:/data
      - ./logs/api:/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - firstmake-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # AI Gateway Service
  aigateway:
    image: ghcr.io/gitraicommerce/firstmake-aigateway:${VERSION:-latest}
    container_name: firstmake-aigateway
    restart: unless-stopped
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - BgGpt__Username=${BGGPT_USERNAME}
      - BgGpt__Password=${BGGPT_PASSWORD}
      - BgGpt__ApiKey=${BGGPT_API_KEY}
      - BgGpt__ApiUrl=http://api.raicommerce.net/v1/completions
      - BgGpt__Model=bg-gpt-7b
      - Tesseract__DataPath=/usr/share/tesseract-ocr/5/tessdata
      - Tesseract__Languages=bul+eng
    volumes:
      - ./logs/aigateway:/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - firstmake-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # UI Service (Nginx)
  ui:
    image: ghcr.io/gitraicommerce/firstmake-ui:${VERSION:-latest}
    container_name: firstmake-ui
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - api
      - aigateway
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - firstmake-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Monitoring - Prometheus (optional)
  prometheus:
    image: prom/prometheus:latest
    container_name: firstmake-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    networks:
      - firstmake-network
    profiles:
      - monitoring

  # Monitoring - Grafana (optional)
  grafana:
    image: grafana/grafana:latest
    container_name: firstmake-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - prometheus
    networks:
      - firstmake-network
    profiles:
      - monitoring

networks:
  firstmake-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
